baseURL = "https://wifiasdf.github.io/"
languageCode = "zh-cn"
title = "WiFiMG的技术博客"
hasCJKLanguage = true
defaultContentLanguage = "zh-cn"

theme = "stack"

# 忽略Raw HTML警告
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML", "JSON"]
    section = ["HTML", "JSON"]
