[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2
    [main.params]
        icon = "categories"

[[main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = 3
    [main.params]
        icon = "search"

[[main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
    [main.params]
        icon = "user"
