mainSections = ["post"]
rssFullContent = true
favicon = "img/logo.png"

[footer]
    since = 2025
    customText = "Made with â¤ï¸ by WiFiMG"

[sidebar]
    emoji = "ğŸ’»"
    subtitle = "è®°å½•æŠ€æœ¯ï¼Œåˆ†äº«çŸ¥è¯†"
    avatar = "img/logo.png"

[article]
    headingAnchor = true
    math = false
    toc = true
    readingTime = true

    [article.license]
        enabled = true
        default = "æœ¬æ–‡é‡‡ç”¨ CC BY-NC-SA 4.0 è®¸å¯åè®®"

[widgets]
    homepage = [
        { type = "search" },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled = false
    provider = ""

[colorScheme]
    toggle = true
    default = "auto"

[imageProcessing.cover]
    enabled = true

[imageProcessing.content]
    enabled = true

[seo]
    # SEOä¼˜åŒ–
    enabled = true
