mainSections = ["post"]
rssFullContent = true
favicon = "img/logo.png"

[footer]
    since = 2025

[sidebar]
    emoji = ""
    subtitle = "记录技术，分享知识"
    avatar = "img/logo.png"

[article]
    [article.license]
        enabled = true
        default = "本文采用 CC BY-NC-SA 4.0 许可协议"

[widgets]
    homepage = [
        { type = "search" },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled = false
    provider = ""

[colorScheme]
    toggle = true
    default = "auto"

[imageProcessing.cover]
    enabled = true

[imageProcessing.content]
    enabled = true
